### ISSUE TITLE
Comment API status

### ISSUE THREAD

**Issue by avivace** [dmg01/homebrewhub#10]
Aight, this wasn't as trivial as we expected, since a lot more factors appeared while implementing the basic routes.

I guess we need to do this the long way round: I propose to stop the development here and move to a separate module.

Priorities are:

- Basic `view` and `edit` routes (backend)
- Basic frontend rendering of the comment tree

We could then proceed to decide on stateful actions (backend side):

- How a delete action should be perfomed and how affects the parent comment and replies
- Voting system
- Comments tree handling

Does this makes sense to you, @dennib ?

**Comment by dennib** [comment]
As discussed yesterady I will continue the development on **comment-api** branch, we should be close to a basic functional version of "*Comment System*"

**Comment by dennib** [comment]
Update:

- [897c133](https://github.com/dmg01/homebrewhub/commit/897c133e1cc8fba2ce8e3d4e2f008e5742ef9c0e) adds **/add/** route for comment posting
- [4989cf0](https://github.com/dmg01/homebrewhub/commit/4989cf0b13501fcb16f866047b5273a6a6a2c67a) **/view/** method is now complete, it responds with comments and comments related info in form of JSON data, comments tree template is rendered completely on frontend now

Still missing correct visual behavior for the moment a comment has been added, I will continue there and then I'll focus on **/edit/** route.

*Every bit of comment system on "old" routes.js file should be useless now, I'll check and confirm (also removing those parts) later*

**Comment by avivace** [comment]
Gotcha. Confirm that everything I removed on `routes` was just backend/sync rendering and we are now completely async with the API endpoints you mentioned

**Comment by dennib** [comment]
Ok I checked, I can confirm!
Those parts are not needed anymore (or they are rewritten elsewhere).
Comment System functionalities are now completely async with the use of API endopoints mentioned above (for which I still have to write the wiki documentation :P)

**Comment by dennib** [comment]
Update:

- [723dade](https://github.com/dmg01/homebrewhub/commit/723dade01f1dfe7155d078ac089f69a661b09793) adds last expected route: /edit/

I'm ready to merge :)

**Comment by avivace** [comment]
Nicely done. Go ahead.
