### ISSUE TITLE
Change "Games" menu item

### ISSUE THREAD

**Issue by tobiasvl** [dmg01/homebrewhub#14]
The menu item "Games", which links to https://gbhh.avivace.com/games, can potentially contain other things than games. (We have categories for games, demos and "homebrew", which is kind of a weird catch-all since everything here is homebrew.) The menu item should probably be renamed to just "List" or "Database" (the name of the repo containing them) or something.

**Comment by avivace** [comment]
Ok. Naming.
Everything in the project is by definition an "homebrew" but I chose to use it to categories everything non-game and non-demo.

The top menu is kinda empty, how about having `Games | Demos | Tools` linking to each category
