### ISSUE TITLE
Dates should follow ISO 8601

### ISSUE THREAD

**Issue by tobiasvl** [dmg01/homebrewhub#6]
The dates in [dmg01/database](https://github.com/dmg01/database) should be parsed as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`2017-12-07`) instead of the American date format (`12/07/2017`).

See also https://github.com/dmg01/database/issues/7

**Comment by avivace** [comment]
Makes sense. We will probably use Mongoose "Date" object so we will be able to make use of the sorting function on it, but the shown dates (frontend) and how they should be parsed from the JSON database can be arbitrary and we can adopt ISO 8601.

**Comment by avivace** [comment]
Done, we're using Moment to display date/time as the browser, while we require ISO 8601 formatted date in the [database](https://github.com/dmg01/database).
